export const Colors = {
  background: '#FAFAFA',
  surface: '#FFFFFF',
  surfaceDim: '#F5F5F5',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerLow: '#FAFAFA',
  surfaceContainer: '#FFFFFF',
  surfaceContainerHigh: '#F5F5F5',
  surfaceContainerHighest: '#EFEFEF',
  surfaceBright: '#FFFFFF',
  surfaceVariant: '#F5F5F5',
  onSurface: '#000000',
  onSurfaceVariant: '#737373',
  primary: '#000000',
  primaryContainer: '#E5E5E5',
  inversePrimary: '#FFFFFF',
  accent: '#000000',
  onPrimary: '#FFFFFF',
  secondary: '#000000',
  secondaryContainer: '#F5F5F5',
  onSecondary: '#FFFFFF',
  tertiary: '#525252',
  tertiaryContainer: '#E5E5E5',
  error: '#FF4E4E',
  errorContainer: '#FFF0F0',
  outline: '#A3A3A3',
  outlineVariant: '#E5E5E5',
} as const
